# Generated by Django 5.2.6 on 2025-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
