name: Django Docker Deploy

on:
  push:
    branches: [ "master", "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Restart Docker
        run: |
          cp /home/vboxuser/django_bear.env django_test/.env
          docker-compose up -d --build