name: Django Docker Deploy

on:
  push:
    branches: [ "master", "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Restart Docker
        run: |
          # Эта команда сама найдет твой docker-compose.yml и обновит проект
          docker compose up -d --build